# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-10 18:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userfavorite',
            old_name='name',
            new_name='user',
        ),
    ]
